/** Keywords and common function names for SQL editor autocomplete (SQLite + libSQL extras). */
export const SQL_EDITOR_KEYWORDS = [
  "SELECT",
  "FROM",
  "WHERE",
  "ORDER BY",
  "GROUP BY",
  "HAVING",
  "LIMIT",
  "OFFSET",
  "INSERT",
  "INTO",
  "VALUES",
  "UPDATE",
  "SET",
  "DELETE",
  "CREATE",
  "ALTER",
  "DROP",
  "TABLE",
  "VIEW",
  "INDEX",
  "TRIGGER",
  "PRIMARY KEY",
  "FOREIGN KEY",
  "REFERENCES",
  "UNIQUE",
  "CHECK",
  "NOT NULL",
  "DEFAULT",
  "WITH",
  "RECURSIVE",
  "JOIN",
  "LEFT JOIN",
  "RIGHT JOIN",
  "INNER JOIN",
  "OUTER JOIN",
  "CROSS JOIN",
  "UNION",
  "UNION ALL",
  "EXCEPT",
  "INTERSECT",
  "PRAGMA",
  "EXPLAIN",
  "ANALYZE",
  "ATTACH",
  "DETACH",
  "BEGIN",
  "COMMIT",
  "ROLLBACK",
  "SAVEPOINT",
  "RELEASE",
  "json_extract",
  "json_set",
  "json_remove",
  "json_array",
  "json_object",
  "fts5",
  "bm25",
  "highlight",
  "snippet",
  "uuid",
  "uuid_v4",
  "uuid_v7",
  "vector",
  "vector_distance_cos",
  "vector_distance_l2",
  "vector_distance_dot",
  "stddev",
  "variance",
  "now",
  "unixepoch",
  "datetime",
  "julianday",
  "strftime",
  "cdc_current_timestamp",
];
