import { promises as fs } from "node:fs";
import path from "node:path";
import { ensureLibsqlNativePackage } from "./ensure-libsql-native-package";
import { libsqlPackageForBunTarget } from "./libsql-embed-packages";

const rootDir = path.resolve(import.meta.dir, "..");
const distDir = path.join(rootDir, "dist", "targets");
const embedPath = path.join(rootDir, "src", "libsql-native.generated.ts");

await fs.mkdir(distDir, { recursive: true });

/** Windows arm64 has no `@libsql/win32-arm64` prebuild yet — omit until libsql-js ships one. */
const TARGETS: { bunTarget: string; platform: string }[] = [
  { bunTarget: "bun-darwin-arm64", platform: "darwin-arm64" },
  { bunTarget: "bun-darwin-x64", platform: "darwin-x64" },
  { bunTarget: "bun-linux-x64", platform: "linux-x64" },
  { bunTarget: "bun-linux-arm64", platform: "linux-arm64" },
  { bunTarget: "bun-windows-x64", platform: "win32-x64" },
];

async function readLibsqlNativeVersion(): Promise<string> {
  const libsqlPkg = path.join(rootDir, "node_modules", "libsql", "package.json");
  const raw = await fs.readFile(libsqlPkg, "utf8");
  const j = JSON.parse(raw) as { optionalDependencies?: Record<string, string> };
  const v = j.optionalDependencies?.["@libsql/darwin-arm64"];
  if (typeof v !== "string") {
    throw new Error("Could not read @libsql/darwin-arm64 version from libsql optionalDependencies");
  }
  return v.replace(/^[\^~]/, "");
}

let nativeVersion: string;
try {
  nativeVersion = await readLibsqlNativeVersion();
} catch {
  console.error("Run `bun install` before scripts/release.ts so node_modules/libsql exists.");
  process.exit(1);
}

let releaseFailed: unknown;

try {
  for (const { bunTarget, platform } of TARGETS) {
    const libsqlPkg = libsqlPackageForBunTarget(bunTarget);
    if (!libsqlPkg) {
      throw new Error(`No libsql native package mapped for ${bunTarget}`);
    }

    await ensureLibsqlNativePackage(rootDir, libsqlPkg, nativeVersion);

    await fs.writeFile(
      embedPath,
      `// Auto-generated by scripts/release.ts for ${bunTarget} — static import embeds N-API addon in compiled binary.
// @see https://bun.com/docs/bundler/executables#embed-n-api-addons
import "${libsqlPkg}";
`,
      "utf8"
    );

    const outfile = path.join(
      distDir,
      platform.startsWith("win32-") ? `sqlitey-${platform}.exe` : `sqlitey-${platform}`
    );

    const buildProc = Bun.spawn(
      [
        "bun",
        "build",
        "src/index.ts",
        "--compile",
        `--target=${bunTarget}`,
        "--outfile",
        outfile,
      ],
      { cwd: rootDir, stdout: "inherit", stderr: "inherit" }
    );

    const buildExit = await buildProc.exited;
    if (buildExit !== 0) {
      throw new Error(`Build failed for ${platform} (target: ${bunTarget}) with exit code ${buildExit}`);
    }

    console.log("Built", platform);
  }
} catch (error) {
  releaseFailed = error;
  console.error("Release build failed:", error);
} finally {
  const restore = Bun.spawn(["bun", "run", path.join(rootDir, "scripts", "write-libsql-embed.ts")], {
    cwd: rootDir,
    stdout: "inherit",
    stderr: "inherit",
  });
  await restore.exited;
  const reinstall = Bun.spawn(["bun", "install"], { cwd: rootDir, stdout: "inherit", stderr: "inherit" });
  await reinstall.exited;
}

if (releaseFailed) {
  process.exit(1);
}

console.log("Built all platforms");
