#!/usr/bin/env bun
/**
 * Writes `src/libsql-native.generated.ts` with a static import of the host's `@libsql/*` package
 * so `bun run src/index.ts` resolves the correct native addon. Release builds overwrite this per target.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { libsqlPackageForHost } from "./libsql-embed-packages";

const rootDir = path.resolve(import.meta.dir, "..");
const outFile = path.join(rootDir, "src", "libsql-native.generated.ts");

const pkg = libsqlPackageForHost();
if (!pkg) {
  const body = `// Auto-generated by scripts/write-libsql-embed.ts — libsql has no prebuilt native addon for this OS/arch.
// Run on macOS, Linux x64/arm64, or Windows x64.
export {};
`;
  await fs.writeFile(outFile, body, "utf8");
  console.warn("write-libsql-embed: no @libsql package for this platform; generated empty stub.");
  process.exit(0);
}

const body = `// Auto-generated by scripts/write-libsql-embed.ts — do not edit by hand.
// Static import so Bun can embed the N-API addon in \`bun build --compile\` binaries.
import "${pkg}";
`;

await fs.writeFile(outFile, body, "utf8");
console.log("write-libsql-embed:", outFile, "→", pkg);
